import { strict as assert } from 'node:assert';
import { createState, tick } from '../../app/mariomortille/simulation.ts';
const input = { direction: 0, jump: false, jumpPressed: false, run: false, downPressed: false, powerPressed: false };
const level = { id: 'test', width: 1000, spawn: { x: 32, y: 200 }, tiles: Array.from({ length: 63 }, (_, i) => ({ x: i * 16, y: 304, kind: 'ground' })), pickups: [], checkpoint: 500, goal: 900 };
const s = createState(level);
for (let i = 0; i < 60; i++) tick(s, level, input);
assert.equal(s.player.y, 262); assert.equal(s.player.grounded, true);
tick(s, level, { ...input, jump: true, jumpPressed: true });
assert.ok(s.player.vy < 0); assert.ok(s.events.includes('jump'));
const jump = (hold) => { const t = createState(level); t.player.y = 262; t.player.grounded = true; let highest = 262; for (let i = 0; i < 60; i++) { tick(t, level, { ...input, jumpPressed: i === 0, jump: hold || i === 0 }); highest = Math.min(highest, t.player.y); } return highest; };
assert.ok(jump(true) < jump(false) - 15, 'held jump travels higher');
const equipment = createState({ ...level, pickups: [{ id: 'shoe', x: 32, y: 260, kind: 'turbo', collected: false }] });
equipment.player.y = 262; equipment.player.grounded = true;
tick(equipment, level, input); assert.equal(equipment.player.power, 'turbo');
tick(equipment, level, { ...input, powerPressed: true }); assert.ok(equipment.player.boost > 0);
const finish = createState(level); finish.player.x = 905; finish.player.y = 262; finish.player.grounded = true;
tick(finish, level, input); const score = finish.score; tick(finish, level, input); assert.equal(finish.score, score); assert.equal(finish.won, true);
console.log('Passed: ground collision, variable jump, automatic equipment, boost, one-time finish reward.');
const enemyLevel = { ...level, enemies: [{ id: 'one', x: 100, y: 284, left: 100, right: 100, direction: 1, defeated: false }] };
const hit = createState(enemyLevel); hit.player.x = 96; hit.player.y = 262; hit.player.power = 'turbo';
tick(hit, enemyLevel, input); assert.equal(hit.player.power, 'none'); assert.equal(hit.player.health, 3, 'power absorbs the first hit');
tick(hit, enemyLevel, input); assert.equal(hit.player.health, 3, 'invulnerability prevents consecutive damage');
const stomp = createState(enemyLevel); stomp.player.x = 100; stomp.player.y = 240; stomp.player.vy = 180;
tick(stomp, enemyLevel, input); assert.equal(stomp.enemies[0].defeated, true); assert.equal(stomp.score, 250); assert.ok(stomp.player.vy < 0);
const checkpoint = createState(level); checkpoint.player.x = 505; checkpoint.player.y = 262; checkpoint.score = 300;
tick(checkpoint, level, input); assert.equal(checkpoint.savedScore, 300); checkpoint.score = 900; checkpoint.player.y = 550;
tick(checkpoint, level, input); assert.equal(checkpoint.score, 300, 'retry restores checkpoint score to avoid farming'); assert.equal(checkpoint.player.x, checkpoint.checkpointSpawn.x);
console.log('Passed: power absorption, damage cooldown, enemy stomp bounce, checkpoint score rollback.');
const fire = createState(level); fire.player.y = 262; fire.player.power = 'ember';
tick(fire, level, { ...input, powerPressed: true }); assert.equal(fire.projectiles.length, 1);
tick(fire, level, { ...input, powerPressed: true }); assert.equal(fire.projectiles.length, 1, 'fire cooldown limits shots');
let bounced = false;
for (let i = 0; i < 50; i++) { tick(fire, level, input); if (fire.projectiles.some(p => p.vy < -150)) bounced = true; }
assert.ok(bounced, 'ember projectile bounces on floor');
const glide = createState(level); glide.player.y = 0; glide.player.vy = 300; glide.player.power = 'cloud';
tick(glide, level, { ...input, jump: true }); assert.ok(glide.player.vy <= 85, 'cloud jacket caps descending speed');
const armorLevel = { ...level, tiles: [{ x: 32, y: 280, kind: 'reinforced' }] };
const armor = createState(armorLevel); armor.player.y = 230; armor.player.pound = 1; armor.player.power = 'cobalt';
tick(armor, armorLevel, input); assert.equal(armor.tiles.length, 0, 'cobalt pound breaks reinforced floor');
const bare = createState(armorLevel); bare.player.y = 230; bare.player.pound = 1;
tick(bare, armorLevel, input); assert.equal(bare.tiles.length, 1, 'ordinary pound cannot break reinforced floor');
const secrets = createState({ ...level, pickups: [{ id: 'star', x: 32, y: 260, kind: 'secret', collected: false }] }); secrets.player.y = 262;
tick(secrets, level, input); tick(secrets, level, input); assert.equal(secrets.score, 1000); assert.equal(secrets.player.power, 'none');
console.log('Passed: fire cooldown and bounce, cloud glide, cobalt-only break, secret reward once.');
